### ISSUE TITLE
Difference in kcpassword file

### ISSUE THREAD

**Issue by thisonethatone** [brunerd/macAdminTools#3]
EDIT: This is for setAutoLogin.sh, I forgot to mention in the original post.

I'm a bit out of my depth here, but I've been troubleshooting why this hasn't worked for my fleet.  I've been testing all of this on MacOS Monterey 12.4 and Catalina 10.15.7.   The script doesn't seem to be working for me (deployed via JAMF or manually), but the GUI (System Preferences) option works fine.

When setting the password with this **script** to "password", I get a kcpassword file that gives a hexdump of:
```
00000000  0d e8 21 50 a5 d3 af 8e  a3 b9 1f 7d 
0000000c
```

When setting the auto login password as "password" via the **GUI**, I get a kcpassword file that gives a hexdump of:
```
00000000  0d e8 21 50 a5 d3 af 8e  a3 4b e4 9e 
0000000c
```

Another example:
password "123/" via **script**:
```
00000000  4c bb 61 0c d2 bc dd ea  a3 b9 1f 7d 
0000000c
``` 

password "123/" via **GUI**:
```
00000000  4c bb 61 0c d2 5b 50 9c  f9 97 7c 4e 
0000000c
```

Final example:
password "abcdefghijklmnopqrstuvwxyz" via **script**:
```
00000000  1c eb 31 47 b7 da ba 82  ca d3 74 11 e4 3c 4c a2 
00000010  cd af 99 d7 cc 69 f1 2b  59 d2 bc dd ea a3 b9 1f 
00000020  7d 89 52                                     
00000023
```

password "abcdefghijklmnopqrstuvwxyz" via **GUI**:
```
00000000  1c eb 31 47 b7 da ba 82  ca d3 74 11 e4 3c 4c a2 
00000010  cd af 99 d7 cc 69 0a f1  2b 59 d2 1f 87 cf fe bc 
00000020  08 25 60 0c             
00000024
```

**Comment by thisonethatone** [comment]
After reading up on this more, this is not an issue but is working as designed.  After the password length and null byte the data doesn't matter.

**Comment by brunerd** [comment]
@thisonethatone you might want to update to a newer version, as there are "unlucky" passwords (like PARTY) where the few ASCII characters the cipher has collide with the same letter in a password and it produces a null which the bash script did not handle properly. It does now 😅 check it out: [setAutoLogin.sh](https://github.com/brunerd/macAdminTools/blob/main/Scripts/setAutoLogin.sh) if you use Jamf then that's been updated too [setAutoLogin.jamf.sh](https://github.com/brunerd/macAdminTools/blob/main/Jamf/scripts/setAutoLogin.jamf.sh)
