### ISSUE TITLE
setAutoLogin.jamf.sh Won't work for guest accounts

### ISSUE THREAD

**Issue by maathieu** [brunerd/macAdminTools#4]
If I try using the script with a guest account (login: guest / password empty), the script will fail saying "Invalid password for 'guest', exiting."

Testing on Catalina 10.15.7

Any help?

**Comment by brunerd** [comment]
Ah, good catch @maathieu it doesn't! Or rather it _didn't_ – both scripts support Guest it now:
[setAutoLogin.jamf.sh](https://github.com/brunerd/macAdminTools/blob/main/Jamf/scripts/setAutoLogin.jamf.sh)
[setAutoLogin.sh](https://github.com/brunerd/macAdminTools/blob/main/Scripts/setAutoLogin.sh)

I made it case sensitive so you **must** use `Guest` for the username argument, just in case someone else has some weird edge case where they are "rolling their own" `guest` account or something like that.

Also, it will also enable the Guest account automatically versus the normal operation where if a user does **not** exist it will exit.

At it's core these are the two commands it runs to enable Guest and set autologin:
```
sysadminctl -guestAccount on
defaults write /Library/Preferences/com.apple.loginwindow autoLoginUser Guest
```

Now it's in the script, so it should cover all bases now! 🎉
