### ISSUE TITLE
iCloud Private Relay Status Checker - Doesn't seem to be working correctly

### ISSUE THREAD

**Issue by aburrow** [brunerd/macAdminTools#5]
Trying to use this script to verify whether or not cloud relay is enabled for Mac users.
The script always reports that "iCloud Private Relay is: OFF"

I believe the issue is related to 
`	childData=$(/usr/libexec/PlistBuddy -c "print :" /dev/stdin 2>/dev/null <<< $(plutil -extract "${key}" xml1 -o - /dev/stdin <<< "${parentData}" | xmllint --xpath "string(//data)" - | base64 --decode | plutil -convert xml1 - -o -))
`
When I echo the results of $childData I get "Error Reading File: /dev/stdin"

**Comment by brunerd** [comment]
Hey there - I'm not having this issue? I've tested on both 13.6.3 and 14.2.1 and both report correctly when iCloud Relay is On/Off.

In your example, you'll have to note that `childData` relies on the variables `parentData` and `key` and `parentData` relies on `domain`... so for you to really test out `childData` it'd need to look like this

```
#parent pref domain
domain="com.apple.networkserviceproxy"
#key that contains base64 encoded Plist within parent domain
key="NSPServiceStatusManagerInfo"
#child key within base64 embedded plist
childKey="PrivacyProxyServiceStatus"

#get the top level data from the main domain
parentData=$(launchctl asuser "$(stat -f %u /dev/console)" sudo -u "$(stat -f %Su /dev/console)" defaults export "${domain}" -)

#export the base64 encoded data within the key as PlistBuddy CF style for grepping (it resists JSON extraction)
childData=$(/usr/libexec/PlistBuddy -c "print :" /dev/stdin 2>/dev/null <<< "$(plutil -extract "${key}" xml1 -o - /dev/stdin <<< "${parentData}" | xmllint --xpath "string(//data)" - | base64 --decode | plutil -convert xml1 - -o -)")

echo "${childData}"
```

Which has yet more data inside to be extracted to `keyStatusCF` which end up being a 1 or 0.

I tested this out in Ventura 13.6.3 and finally upgrading my personal Mac to Ventura 14.2.1 and it worked in both cases

<img width="757" alt="image" src="https://github.com/brunerd/macAdminTools/assets/9872375/4dacbbeb-b821-4f70-8ce9-541791f7c6b9">

<img width="700" alt="image" src="https://github.com/brunerd/macAdminTools/assets/9872375/f10831be-c9b6-4019-98c8-0137573e1f3d">



<img width="901" alt="image" src="https://github.com/brunerd/macAdminTools/assets/9872375/69b77a31-0009-4970-91c2-699e03a0a045">

<img width="897" alt="image" src="https://github.com/brunerd/macAdminTools/assets/9872375/31b182f2-bd3f-435b-b22a-f99a2e4595a3">

Perhaps try adding `set -x` in the script or function to see what's occurring? This will enable xtrace output so you can see each step in the script. Not sure of _how_ you are running this script and in what context, perhaps `PATH` isn't set correctly? I admit the script assumes `PATH` will be set so it can find things like `awk`, `plutil`, `launchctl` `defaults` etc... Perhaps add an `echo $PATH` in there when you run it to see if it's not set correctly? One last thought is that it requires a user to be **logged in** to function correctly, are any of the failures on logged out Macs? (there's ways to get the last user though if that's the case let me know and I could add that)

"Not able to reproduce." though... 🤔
